apiVersion: batch/v1
kind: CronJob
metadata:
  name: node-metrics-cronjob
spec:
  schedule: "*/1 * * * *" # Runs every minute, can be changed as needed
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: node-metrics
            image: chinmaykubal/collect_metrics
            env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            volumeMounts:
            - name: metrics
              mountPath: /metrics
          restartPolicy: OnFailure
          volumes:
          - name: metrics
            persistentVolumeClaim:
              claimName: metrics-pvc
