apiVersion: v1
kind: PersistentVolume
metadata:
  name: metrics-pv
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /mnt/metrics

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metrics-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard


